version: '3.8'

services:
  backend:
    build:
      context: ./finance_manager
      dockerfile: .docker/Dockerfile
    volumes:
      - ./finance_manager:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://user:password@postgres:5432/dbname
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "4707:4707"
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: password 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./front-finance
      dockerfile: .docker/Dockerfile
    volumes:
      - ./front-finance:/app
      - /app/node_modules
    ports:
      - "5173:5173" 
    command: npm run dev -- --host
    depends_on:
      - backend

volumes:
  postgres_data: